# Generated by Django 4.2.4 on 2023-08-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat', models.PositiveIntegerField()),
                ('face', models.PositiveIntegerField()),
                ('top', models.PositiveIntegerField()),
                ('bottom', models.PositiveIntegerField()),
            ],
        ),
    ]
