# Generated by Django 4.2.4 on 2023-08-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='party_url',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='url',
            field=models.TextField(default='', unique=True),
        ),
    ]
