# Generated by Django 4.2.4 on 2023-08-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PartyApp', '0001_initial'),
        ('UserApp', '0001_initial'),
        ('CharacterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_hosted', to='UserApp.user'),
        ),
        migrations.AddField(
            model_name='party',
            name='participants',
            field=models.ManyToManyField(related_name='parties', through='PartyApp.Seat', to='CharacterApp.character'),
        ),
    ]
