# Generated by Django 4.2.4 on 2023-08-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0001_initial'),
        ('PartyApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='seats_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='party',
            name='url',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='parties', through='PartyApp.Seat', to='CharacterApp.character'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterApp.character'),
        ),
    ]
