# Generated by Django 4.2.4 on 2023-08-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0001_initial'),
        ('PartyApp', '0003_party_seats_count_party_url_alter_party_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='participants',
            field=models.ManyToManyField(related_name='parties', through='PartyApp.Seat', to='CharacterApp.character'),
        ),
    ]
